#!/bin/bash

##
# Parameters are position-based and include:
#
# 1 - Host name of remote server to start.
# 2 - Path to data directory on remote server.
#
# This script must be in PGDATA
#set -e

if [ ! -d /var/log/pg ] ; then
 sudo mkdir /var/log/pg
 sudo chown postgres:postgres /var/log/pg
fi
LOGFILE=/var/log/pg/pgpool_remote_start.log
PGVER=${PGVER:-11}

echo "Exec pgpool_remote_start.sh at `date`" | tee -a $LOGFILE
PATH=$PATH:/usr/pgsql-${PGVER}/bin/pg_ctl

if [ $# -lt 2 ]; then
    echo "Start a remote PostgreSQL server within pgpool."
    echo
    echo "Usage: $0 REMOTE_HOST REMOTE_PATH"
    echo
    exit 1
fi

remote_host=$1
remote_path=$2
echo "remote_host: ${remote_host}" | tee -a $LOGFILE
echo "remote_path: ${remote_path}" | tee -a $LOGFILE

ssh_options="ssh -p 222 -n -T -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no postgres@$remote_host"
set -x
$ssh_options "/scripts/pg_start.sh" &
echo "sleep 20 after pg_ctl start"
sleep 20
$ssh_options "supervisorctl status all"
exit 0
