#!/bin/bash

##
# Parameters are position-based and include:
#
# 1 - Host name of remote server to start.
# 2 - Path to data directory on remote server.
#
# This script must be in PGDATA
#set -e

if [ ! -d /var/log/pg-utils ] ; then
 sudo mkdir /var/log/pg-utils
 sudo chown postgres:postgres /var/log/pg-utils
fi
LOGFILE=/var/log/pg-utils/pgpool_remote_start.log

echo "Exec pgpool_remote_start.sh at `date`" | tee -a $LOGFILE
PATH=$PATH:/usr/pgsql-10/bin/pg_ctl

if [ $# -lt 2 ]; then
    echo "Start a remote PostgreSQL server within pgpool."
    echo
    echo "Usage: $0 REMOTE_HOST REMOTE_PATH"
    echo
    exit 1
fi

remote_host=$1
remote_path=$2
echo "remote_host: ${remote_host}" | tee -a $LOGFILE
echo "remote_path: ${remote_path}" | tee -a $LOGFILE

ssh_options="ssh -n -T -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no postgres@$remote_host"
set -x
$ssh_options "/usr/pgsql-10/bin/pg_ctl -D ${remote_path} start" &
echo "sleep 20 after pg_ctl start"
sleep 20
$ssh_options "ps -ef"
exit 0
