#!/bin/bash

##
# Parameters are position-based and include:
#
# 1 - Host name of remote server to start.
# 2 - Path to data directory on remote server.
#
# This script must be in PGDATA

if [ ! -d /var/log/pg-utils ] ; then
 sudo mkdir /var/log/pg-utils
 sudo chown postgres:postgres /var/log/pg-utils
fi
LOGFILE=/var/log/pg-utils

echo "Exec pgpool_remote_start at `date`" | tee -a $LOGFILE

if [ $# -lt 2 ]; then
    echo "Start a remote PostgreSQL server within pgpool."
    echo
    echo "Usage: $0 REMOTE_HOST REMOTE_PATH"
    echo
    exit 1
fi

remote_host=$1
remote_path=$2
echo "remote_host: ${remote_host}" | tee -a $LOGFILE
echo "remote_path: ${remote_path}" | tee -a $LOGFILE

#options=$(cat postmaster.opts | sed 's/[^ ]* //;')
#ssh postgres@$remote_host -T "pg_ctl -D $remote_path -o '$options' start" &>/dev/null &
ssh_options="ssh -n -T -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
$ssh_options postgres@$remote_host -T "sudo systemctl restart postgresql-9.6"
